language: d
sudo: false

d:
  - dmd
  - ldc

script:
  - make style_lint
  - dub test --compiler=${DC}
  - cd test
  - dub build --compiler=${DC}
  - ./test --onlyRunTests

notifications:
  email: false
